TK274 -
JigsawAcademyGlobal/JAWS pull request #557
Opened 2021-02-25 13:11 UTC by karuna835

- Reinstate option for Alumni status.

2021-02-26 04:10 UTC, kailasb commented on app/apis/btcapi/subs/edit.php
> +	}
user ternary operator

2021-02-26 04:10 UTC, kailasb commented on b/js/app.js
> +						}
use ternary operator

2021-02-26 04:11 UTC, kailasb commented on b/js/app.js
> +			}
use ternary operator

2021-02-26 04:11 UTC, kailasb requested changes
check the feedback

2021-03-01 11:19 UTC, karuna835 commented on app/apis/btcapi/subs/edit.php
> +	}
I have used ternary operator

2021-03-01 11:19 UTC, karuna835 commented on b/js/app.js
> +						}
I have used ternary operator

2021-03-01 11:20 UTC, karuna835 commented on b/js/app.js
> +			}
I have used ternary operator

2021-03-01 11:52 UTC, kailasb approved these changes
changes are proper

2021-03-01 12:35 UTC, merged